apiVersion: apps/v1
kind: Deployment
metadata:
  name: proceedtobuydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Proceedtobuy
  template:
    metadata:
      labels:
        app: Proceedtobuy
    spec:
      containers:
      - name: proceedtobuyrepository
        image: containerr1.azurecr.io/proceedtobuyrepository:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: proceedtobuy
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Proceedtobuy
